import type { Product, ProductCategory, Promotion } from '@/types';

export const categories: ProductCategory[] = [
      {
    id: 1,
    slug: 'honey',
    name: 'Honey',
    image: '/categories/honey.jpg',
    description: 'Pure, raw, and natural honey straight from the hive.',
  },
  {
    id: 2,
    slug: 'shea',
    name: 'Shea Butter',
    image: '/categories/shea.jpg',
    description: 'Nourishing shea butter for skin and hair care.',
  },
  {
    id: 8,
    slug: 'wax',
    name: 'Bees Wax',
    image: '/categories/shea.jpg',
    description: 'Nourishing shea butter for skin and hair care.',
  },
  {
    id: 3,
    slug: 'odii',
    name: 'Kitamu Odii',
    image: '/categories/odii.jpg',
    description: 'Rich, locally made groundnut paste blends.',
  },
  {
    id: 4,
    slug: 'oil',
    name: 'Essential Oils',
    image: '/categories/oils.jpg',
    description: 'Therapeutic oils for relaxation and wellness.',
  },
  {
    id: 5,
    name: 'Fresh Fruits',
    slug: 'fruits',
    description: 'Organic seasonal fruits',
    image: 'https://images.pexels.com/photos/1132047/pexels-photo-1132047.jpeg'
  },
  {
    id: 6,
    name: 'Vegetables',
    slug: 'vegetables',
    description: 'Farm-fresh organic vegetables',
    image: 'https://images.pexels.com/photos/1400172/pexels-photo-1400172.jpeg'
  },
  {
    id: 7,
    name: 'Grains & Cereals',
    slug: 'grains',
    description: 'Organic grains and cereals',
    image: 'https://images.pexels.com/photos/1537635/pexels-photo-1537635.jpeg'
  },
];

export const products: Product[] = [
  {
    id: "HNY-030G",
    name: "Kitamu Honey 30g",
    description: "Single-serve 30g pure Ugandan honey — perfect for travel, tea, and tasting.",
    price: 1000,
    // originalPrice: 1200,
    image: "/products/honey-30g.png",
    images: [
      "/products/honey-30g.png",
      "/products/honey-30g-alt1.png"
    ],
    category: categories.find(c => c.slug === 'honey')!,
    inStock: true,
    stockQuantity: 600,
    rating: 4.7,
    reviewCount: 38,
    isOrganic: true,
    origin: "Kisaasi, Gulu, Kitgum",
    weight: "30 g",
    featured: false
  },
  {
    id: "HNY-150G",
    name: "Kitamu Honey 150g",
    description: "Smooth, floral honey from Northern Uganda in a handy 150g jar.",
    price: 5000,
    originalPrice: 6000,
    image: "/products/honey-150g.png",
    images: [
      "/products/honey-150g.png",
      "/products/honey-150g-alt1.jpg"
    ],
    category: categories.find(c => c.slug === 'honey')!,
    inStock: true,
    stockQuantity: 420,
    rating: 4.8,
    reviewCount: 64,
    isOrganic: true,
    origin: "Kisaasi, Gulu, Kitgum",
    weight: "200 g",
    featured: true
  },
  {
    id: "HNY-250G",
    name: "Kitamu Honey 250g",
    description: "Raw, unadulterated honey — ideal for daily use.",
    price: 7000,
    // originalPrice: 8000,
    image: "/products/honey-250g.png",
    images: [
      "/products/honey-250g.png",
      "/products/honey-250g-alt1.jpg"
    ],
    category: categories.find(c => c.slug === 'honey')!,
    inStock: true,
    stockQuantity: 350,
    rating: 4.8,
    reviewCount: 91,
    isOrganic: true,
    origin: "Kisaasi, Gulu, Kitgum",
    weight: "250 g",
    featured: false
  },
  {
    id: "HNY-450G",
    name: "Kitamu Honey 450g",
    description: "Family-size jar of 100% natural honey with balanced sweetness.",
    price: 15000,
    // originalPrice: 17000,
    image: "/products/honey-450g.png",
    images: [
      "/products/honey-450g.png"
    ],
    category: categories.find(c => c.slug === 'honey')!,
    inStock: true,
    stockQuantity: 260,
    rating: 4.9,
    reviewCount: 120,
    isOrganic: true,
    origin: "Kisaasi, Gulu, Kitgum",
    weight: "450 g",
    featured: false
  },
  {
    id: "HNY-1KG",
    name: "Kitamu Honey 1kg",
    description: "Bulk 1kg jar — great value for families and bakers.",
    price: 25000,
    originalPrice: 28000,
    image: "/products/honey-1kg.png",
    images: [
      "/products/honey-1kg.png",
      "/products/honey-1kg-alt1.jpg"
    ],
    category: categories.find(c => c.slug === 'honey')!,
    inStock: true,
    stockQuantity: 180,
    rating: 4.9,
    reviewCount: 154,
    isOrganic: true,
    origin: "Kisaasi, Gulu, Kitgum",
    weight: "1 kg",
    featured: false,
    nutritionalInfo: {
      // servingSize: "100 g",
      calories: 304,
      fat: 0,
      carbs: 82,
      sugar: 82,
      protein: 0,
      fiber:0,
      vitamins:[]
    }
  },
  {
    id: "HNY-1200G",
    name: "Kitamu Honey 1200g",
    description: "1.2kg family pack of raw honey sourced from community beekeepers.",
    price: 35000,
    // originalPrice: 38000,
    image: "/products/honey-1200g.png",
    images: [
      "/products/honey-1200g.png"
    ],
    category: categories.find(c => c.slug === 'honey')!,
    inStock: true,
    stockQuantity: 140,
    rating: 4.8,
    reviewCount: 77,
    isOrganic: true,
    origin: "Kisaasi, Gulu, Kitgum",
    weight: "1.2 kg",
    featured: true
  },
  {
    id: "HNY-6KG",
    name: "Kitamu Honey 6kg (Bulk)",
    description: "6kg food-service bucket — perfect for bakeries and restaurants.",
    price: 150000,
    // originalPrice: 165000,
    image: "/products/honey-6kg.png",
    images: [
      "/products/honey-6kg.png"
    ],
    category: categories.find(c => c.slug === 'honey')!,
    inStock: true,
    stockQuantity: 40,
    rating: 4.9,
    reviewCount: 33,
    isOrganic: true,
    origin: "Kisaasi, Gulu, Kitgum",
    weight: "6 kg",
    featured: false,
  },
  {
    id: "CRUDE-1KG",
    name: "Kitamu Crude Honey 1kg",
    description: "Unfiltered crude honey retaining natural wax and pollen.",
    price: 25000,
    // originalPrice: 28000,
    image: "/products/crude-honey-1kg.png",
    images: [
      "/products/crude-honey-1kg.png"
    ],
    category: categories.find(c => c.slug === 'honey')!,
    inStock: true,
    stockQuantity: 95,
    rating: 4.6,
    reviewCount: 22,
    isOrganic: true,
    origin: "Kisaasi, Gulu, Kitgum",
    weight: "1 kg",
    featured: false
  },
  {
    id: "SHEA-250G",
    name: "Kitamu Shea Butter (Cold-Pressed) 250g",
    description: "Cold-pressed shea butter — moisturizes and nourishes skin and hair.",
    price: 10000,
    // originalPrice: 12000,
    image: "/products/shea-250g.png",
    images: [
      "/products/shea-250g.png",
      "/products/shea-250g-alt1.jpg"
    ],
    category: categories.find(c => c.slug === 'shea')!,
    inStock: true,
    stockQuantity: 300,
    rating: 4.7,
    reviewCount: 58,
    isOrganic: true,
    origin: "Kisaasi, Gulu, Kitgum",
    weight: "250 g",
    featured: true
  },
  {
    id: "SHEA-500G",
    name: "Kitamu Shea Butter (Cold-Pressed) 500g",
    description: "Cold-pressed shea butter — moisturizes and nourishes skin and hair.",
    price: 20000,
    // originalPrice: 12000,
    image: "/products/shea-500g.png",
    images: [
      "/products/shea-500g.png",
      "/products/shea-500g-alt1.jpg"
    ],
    category: categories.find(c => c.slug === 'shea')!,
    inStock: true,
    stockQuantity: 300,
    rating: 4.7,
    reviewCount: 58,
    isOrganic: true,
    origin: "Kisaasi, Gulu, Kitgum",
    weight: "500 g",
    featured: false
  },
  {
    id: "WAX-1KG",
    name: "Kitamu Beeswax 1kg",
    description: "Pure beeswax for candles, cosmetics, and food wraps.",
    price: 30000,
    // originalPrice: 35000,
    image: "/products/wax.png",
    images: [
      "/products/wax.png"
    ],
    category: categories.find(c => c.slug === 'wax')!,
    inStock: true,
    stockQuantity: 120,
    rating: 4.5,
    reviewCount: 19,
    isOrganic: true,
    origin: "Kisaasi, Gulu, Kitgum",
    weight: "1 kg",
    featured: false
  },
  {
    id: "ODII-PN-1KG",
    name: "Kitamu ODII (Peanut) 1kg",
    description: "Traditional peanut (groundnut) paste — smooth and richly roasted.",
    price: 15000,
    // originalPrice: 17000,
    image: "/products/odii-peanut-1kg.png",
    images: [
      "/products/odii-peanut-1kg.png",
      "/products/odii-peanut-1kg-alt1.jpg"
    ],
    category: categories.find(c => c.slug === 'odii')!,
    inStock: true,
    stockQuantity: 210,
    rating: 4.8,
    reviewCount: 88,
    isOrganic: true,
    origin: "Kisaasi, Gulu, Kitgum",
    weight: "1 kg",
    featured: true,
    nutritionalInfo: {
      // servingSize: "100 g",
      calories: 589,
      fat: 50,
      carbs: 16,
      sugar: 4,
      protein: 25,
      vitamins: [],
      fiber: 0
    }
  },
  {
    id: "ODII-SS-1KG",
    name: "Kitamu ODII (Sesame) 1kg",
    description: "Nutty sesame paste (sim-sim) — great for sauces and spreads.",
    price: 20000,
    // originalPrice: 23000,
    image: "/products/odii-sesame-1kg.png",
    images: [
      "/products/odii-sesame-1kg.png"
    ],
    category: categories.find(c => c.slug === 'odii')!,
    inStock: true,
    stockQuantity: 160,
    rating: 4.7,
    reviewCount: 51,
    isOrganic: true,
    origin: "Kisaasi, Gulu, Kitgum",
    weight: "1 kg",
    featured: false,
    nutritionalInfo: {
      // servingSize: "100 g",
      calories: 570,
      fat: 50,
      carbs: 23,
      sugar: 1,
      protein: 18,
      vitamins: [],
      fiber: 0,
    }
  },
  {
    id: 'LMG-OIL',
    name: 'Lemongrass Oil 100ml',
    description: 'Refreshing essential oil for aromatherapy and massage.',
    price: 18000,
    // originalPrice: 20000,
    image: '/products/lemongrass.png',
    images: ['/products/lemongrass.png'],
    category: categories.find(c => c.slug === 'oil')!,
    inStock: true,
    stockQuantity: 25,
    rating: 4.6,
    reviewCount: 17,
    isOrganic: true,
    origin: 'Mityana, Uganda',
    weight: '100ml',
    featured: false,
    nutritionalInfo: {
      calories: 0,
      protein: 0,
      carbs: 0,
      fat: 0,
      fiber: 0,
      sugar: 0,
      vitamins: ['Citral', 'Geraniol']
    }
  },
  // {
  //   id: "ODII-MIX-500G",
  //   name: "Kitamu ODII 500g",
  //   description: "500g ODII — versatile for home cooking and everyday spreads.",
  //   price: 7000,
  //   // originalPrice: 8000,
  //   image: "/products/odii-500g.png",
  //   images: [
  //     "/products/odii-500g.png"
  //   ],
  //   category: categories.find(c => c.slug === 'odii')!,
  //   inStock: true,
  //   stockQuantity: 280,
  //   rating: 4.6,
  //   reviewCount: 44,
  //   isOrganic: true,
  //   origin: "Kisaasi, Gulu, Kitgum",
  //   weight: "500 g",
  //   featured: false,
  //   nutritionalInfo: {
  //     // servingSize: "100 g",
  //     calories: 580,
  //     fat: 49,
  //     carbs: 18,
  //     sugar: 3,
  //     protein: 23,
  //     fiber: 0,
  //   }
  // },
];

// export const products: Product[] = [
//   {
//     id: '1',
//     name: 'Raw Honey 1L',
//     description: 'Unprocessed, natural honey harvested from Ugandan apiaries.',
//     price: 15000,
//     originalPrice: 17000,
//     image: '/products/honey-jar.jpg',
//     images: ['/products/honey-jar.jpg'],
//     category: categories.find(c => c.slug === 'honey')!,
//     inStock: true,
//     stockQuantity: 40,
//     rating: 4.8,
//     reviewCount: 38,
//     isOrganic: true,
//     origin: 'Luwero, Uganda',
//     weight: '1L',
//     featured: true,
//     nutritionalInfo: {
//       calories: 304,
//       protein: 0.3,
//       carbs: 82.4,
//       fat: 0,
//       fiber: 0.2,
//       vitamins: ['Vitamin C', 'Calcium', 'Iron']
//     }
//   },
//   {
//     id: '2',
//     name: 'Raw Honey 20L',
//     description: 'Bulk supply of raw organic honey ideal for commercial or long-term use.',
//     price: 180000,
//     originalPrice: 190000,
//     image: '/products/jerrycan.png',
//     images: ['/products/jerrycan.png'],
//     category: categories.find(c => c.slug === 'honey')!,
//     inStock: true,
//     stockQuantity: 15,
//     rating: 4.9,
//     reviewCount: 12,
//     isOrganic: true,
//     origin: 'Luwero, Uganda',
//     weight: '20L',
//     featured: false,
//     nutritionalInfo: {
//       calories: 304,
//       protein: 0.3,
//       carbs: 82.4,
//       fat: 0,
//       fiber: 0.2,
//       vitamins: ['Vitamin C', 'Calcium', 'Iron']
//     }
//   },
//   {
//     id: '3',
//     name: 'Shea Butter 500g',
//     description: 'Rich, unrefined shea butter ideal for moisturizing skin and hair.',
//     price: 12050,
//     originalPrice: 14000,
//     image: '/products/shea.png',
//     images: ['/products/shea.png'],
//     category: categories.find(c => c.slug === 'shea')!,
//     inStock: true,
//     stockQuantity: 30,
//     rating: 4.7,
//     reviewCount: 18,
//     isOrganic: true,
//     origin: 'Northern Uganda',
//     weight: '500g',
//     featured: true,
//     nutritionalInfo: {
//       calories: 884,
//       protein: 0,
//       carbs: 0,
//       fat: 100,
//       fiber: 0,
//       vitamins: ['Vitamin A', 'Vitamin E']
//     }
//   },
//   {
//     id: '4',
//     name: 'Shea Butter 1kg',
//     description: 'Premium shea butter in large quantity, great for skincare routines.',
//     price: 20000,
//     originalPrice: 22000,
//     image: '/products/shea-butter.jpg',
//     images: ['/products/shea-butter.jpg'],
//     category: categories.find(c => c.slug === 'shea')!,
//     inStock: true,
//     stockQuantity: 20,
//     rating: 4.6,
//     reviewCount: 9,
//     isOrganic: true,
//     origin: 'Northern Uganda',
//     weight: '1kg',
//     featured: false,
//     nutritionalInfo: {
//       calories: 884,
//       protein: 0,
//       carbs: 0,
//       fat: 100,
//       fiber: 0,
//       vitamins: ['Vitamin A', 'Vitamin E']
//     }
//   },
//   {
//     id: '5',
//     name: 'Kitamu Odii 250g',
//     description: 'Locally made peanut paste perfect for traditional dishes.',
//     price: 10000,
//     originalPrice: 11000,
//     image: '/products/odii.png',
//     images: ['/products/odii.png'],
//     category: categories.find(c => c.slug === 'odii')!,
//     inStock: true,
//     stockQuantity: 50,
//     rating: 4.4,
//     reviewCount: 25,
//     isOrganic: true,
//     origin: 'Arua, Uganda',
//     weight: '250g',
//     featured: false,
//     nutritionalInfo: {
//       calories: 589,
//       protein: 25,
//       carbs: 20,
//       fat: 50,
//       fiber: 6,
//       vitamins: ['Vitamin B3', 'Vitamin E']
//     }
//   },
//   {
//     id: '6',
//     name: 'Kitamu Odii Mix 500g',
//     description: 'Groundnut paste blend mixed with sesame and spices for rich taste.',
//     price: 16000,
//     originalPrice: 17000,
//     image: '/products/odii-mix.jpg',
//     images: ['/products/odii-mix.jpg'],
//     category: categories.find(c => c.slug === 'odii')!,
//     inStock: true,
//     stockQuantity: 40,
//     rating: 4.5,
//     reviewCount: 14,
//     isOrganic: true,
//     origin: 'Nebbi, Uganda',
//     weight: '500g',
//     featured: true,
//     nutritionalInfo: {
//       calories: 610,
//       protein: 22,
//       carbs: 18,
//       fat: 52,
//       fiber: 5,
//       vitamins: ['Vitamin B6', 'Magnesium']
//     }
//   },
//   {
//     id: '7',
//     name: 'Lemongrass Oil 100ml',
//     description: 'Refreshing essential oil for aromatherapy and massage.',
//     price: 18000,
//     originalPrice: 20000,
//     image: '/products/lemongrass-oil.jpg',
//     images: ['/products/lemongrass-oil.jpg'],
//     category: categories.find(c => c.slug === 'oil')!,
//     inStock: true,
//     stockQuantity: 25,
//     rating: 4.6,
//     reviewCount: 17,
//     isOrganic: true,
//     origin: 'Mityana, Uganda',
//     weight: '100ml',
//     featured: false,
//     nutritionalInfo: {
//       calories: 0,
//       protein: 0,
//       carbs: 0,
//       fat: 0,
//       fiber: 0,
//       vitamins: ['Citral', 'Geraniol']
//     }
//   },
//   {
//     id: '8',
//     name: 'Lemongrass Oil 50ml',
//     description: 'Soothing lemongrass essential oil, great for calming and freshness.',
//     price: 10000,
//     originalPrice: 12000,
//     image: '/products/lemongrass.png',
//     images: ['/products/lemongrass.png'],
//     category: categories.find(c => c.slug === 'oil')!,
//     inStock: true,
//     stockQuantity: 30,
//     rating: 4.3,
//     reviewCount: 11,
//     isOrganic: true,
//     origin: 'Mityana, Uganda',
//     weight: '50ml',
//     featured: true,
//     nutritionalInfo: {
//       calories: 0,
//       protein: 0,
//       carbs: 0,
//       fat: 0,
//       fiber: 0,
//       vitamins: ['Citral', 'Geraniol']
//     }
//   },
// ];

export const promotions: Promotion[] = [
  {
    id: '1',
    title: 'Fresh Fruits Weekend Sale',
    description: 'Get 20% off on all organic fruits this weekend!',
    image: 'https://images.pexels.com/photos/1132047/pexels-photo-1132047.jpeg',
    discount: 20,
    validUntil: new Date('2024-12-31'),
    isActive: true
  },
  {
    id: '2',
    title: 'Free Delivery on Orders Over UGX 50,000',
    description: 'Enjoy free delivery within Kampala for orders above UGX 50,000',
    image: 'https://images.pexels.com/photos/4393021/pexels-photo-4393021.jpeg',
    discount: 0,
    validUntil: new Date('2024-12-31'),
    isActive: true
  }
];


